document.writeln("<!DOCTYPE html>");
document.writeln("<html lang=\"zh-cn\">");
document.writeln("<head>");
document.writeln("<link rel=\"stylesheet\" href=\"https://lib.baomitu.com/twitter-bootstrap/4.3.1/css/bootstrap.min.css\">");
document.writeln("<link rel=\"stylesheet\" href=\"https://lib.baomitu.com/prettify/latest/prettify.css\">");
document.writeln("<script rel=\"stylesheet\" src=\"https://lib.baomitu.com/layer/3.1.1/mobile/layer.js\"></script>");
document.writeln("<style type=\"text/css\">");
document.writeln("    body{font-family:-apple-system,BlinkMacSystemFont,\"Segoe UI\",Roboto,\"Helvetica Neue\",Arial,\'sans-serif\';background: url(https://api.uomg.com/api/image.lofter?format=images); background-size: cover;}");
document.writeln("    @font-face {font-family: \'webfont_2\';");
document.writeln("        src: url(\'//at.alicdn.com/t/webfont_bar76uyhrpd.eot\'); /* IE9*/");
document.writeln("        src: url(\'//at.alicdn.com/t/webfont_bar76uyhrpd.eot?#iefix\') format(\'embedded-opentype\'), /* IE6-IE8 */");
document.writeln("        url(\'//at.alicdn.com/t/webfont_bar76uyhrpd.woff\') format(\'woff\'), /* chrome、firefox */");
document.writeln("        url(\'//at.alicdn.com/t/webfont_bar76uyhrpd.ttf\') format(\'truetype\'), /* chrome、firefox、opera、Safari, Android, iOS 4.2+*/");
document.writeln("        url(\'//at.alicdn.com/t/webfont_bar76uyhrpd.svg#思源黑体-极细\') format(\'svg\'); /* iOS 4.1- */");
document.writeln("    }");
document.writeln("    .text-center{text-align: center;}");
document.writeln("    .text-white{color: #FFF;}");
document.writeln("    .header,.footer{margin: 30px;color:#fff;}");
document.writeln("    .title1{font-size: 20px;}");
document.writeln("    .title2{font-size: 24px;font-family:\"webfont_2\" !important;}");
document.writeln("    .jumbotron{margin: auto;text-align: center;background-color: rgba(255, 255, 255, .3);}");
document.writeln("    .jumbotron input[type=file] {opacity:0;width:102px;height:31px;position:absolute;display:inline-block;}");
document.writeln("    .preview {color: #fff;}");
document.writeln("    .preview img {max-width: 10%;}");
document.writeln("    .preview p {word-break: break-all;word-wrap: break-word;font-size: 13px !important;}");
document.writeln("    .form-control:focus{background-color: rgba(255, 255, 255, .3);}");
document.writeln("</style>");
document.writeln("</head>");
document.writeln("<body>");
document.writeln("    <div class=\"container-fluid\">");
document.writeln("        <div class=\"row-fluid\">");
document.writeln("            <div class=\"span12 header text-center\">");
document.writeln("                <p class=\"title1\">免费-免费</p>");
document.writeln("                <p class=\"title2\">阿里巴巴图片外链服务 稳定不掉线 免费使用</p>");
document.writeln("            </div>");
document.writeln("            <div class=\"col-md-8 col-xs-10 jumbotron\" style=\"margin:auto;\">");
document.writeln("                <div class=\"mselector\">");
document.writeln("                    <input type=\"file\" accept=\"image/*\" multiple>");
document.writeln("                    <button type=\"button\" class=\"btn btn-primary btn-sm\">选择本地图片</button>");
document.writeln("                    <button type=\"button\" class=\"btn btn-primary btn-sm\" data-toggle=\"modal\" data-target=\"#url_upload_model\">上传远程图片</button>                   ");
document.writeln("                </div><hr>");
document.writeln("                <textarea id=\"url-res-txt\" class=\"form-control\" rows=\"5\" placeholder=\"上传后的图片外链地址将显示在此处，下方会同时显示外链地址和预览图。\"></textarea>");
document.writeln("                <div class=\"preview\">");
document.writeln("                    <hr>");
document.writeln("                </div>");
document.writeln("                <span class=\"title1\"><b>温馨提示:</b> 本站不存储且无权管理上传的图源，图源均存放在新浪服务器，切勿上传违反法规图源，否则后果自负。</span>");
document.writeln("            </div>");
document.writeln("            <div class=\"footer text-center\">");
document.writeln("                <a target=\"_blank\" class=\"title1\">© 2019 熊猫图床</a>");
document.writeln("            </div>");
document.writeln("        </div>");
document.writeln("    </div>");
document.writeln("    <div id=\"url_upload_model\" class=\"modal fade\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"myModalLabel\" aria-hidden=\"true\">");
document.writeln("    	<div class=\"modal-dialog\">");
document.writeln("    		<div class=\"modal-content\">");
document.writeln("    			<div class=\"modal-header\">");
document.writeln("    				<h4 class=\"modal-title\" id=\"myModalLabel\">上传远程图片</h4>");
document.writeln("    			</div>");
document.writeln("    			<div class=\"modal-body\">");
document.writeln("    				<p class=\"lead\">");
document.writeln("    					请在下方输入远程图片地址~每行一个~");
document.writeln("    				</p>");
document.writeln("    				<textarea class=\"form-control\" name=\"urls\" rows=\"3\" id=\"urls\"></textarea>");
document.writeln("    			</div>");
document.writeln("    			<div class=\"modal-footer\">");
document.writeln("    				<button type=\"button\" class=\"btn btn-default\" data-dismiss=\"modal\">关闭</button>");
document.writeln("    				<button type=\"button\" class=\"btn btn-primary\" onclick=\"url_upload();\">提交</button>");
document.writeln("    			</div>");
document.writeln("    		</div>");
document.writeln("    	</div>");
document.writeln("    </div>");
document.writeln("    <script src=\"https://lib.baomitu.com/jquery/3.4.0/jquery.min.js\" type=\"text/javascript\"></script>");
document.writeln("    <script src=\"https://lib.baomitu.com/twitter-bootstrap/4.3.1/js/bootstrap.min.js\" type=\"text/javascript\"></script>");
document.writeln("    <script type=\"text/javascript\">");
document.writeln("        var url = \'https://api.uomg.com/api/image.ali\';");
document.writeln("        $(document).ready(function() {");
document.writeln("            $(\"input[type=\'file\']\").change(function(e) {");
document.writeln("                file_upload(this.files)");
document.writeln("            });");
document.writeln("            var obj = $(\'body\');");
document.writeln("            obj.on(\'dragenter\', function(e) {");
document.writeln("                e.stopPropagation();");
document.writeln("                e.preventDefault()");
document.writeln("            });");
document.writeln("            obj.on(\'dragover\', function(e) {");
document.writeln("                e.stopPropagation();");
document.writeln("                e.preventDefault()");
document.writeln("            });");
document.writeln("            obj.on(\'drop\', function(e) {");
document.writeln("                e.preventDefault();");
document.writeln("                file_upload(e.originalEvent.dataTransfer.files)");
document.writeln("            });");
document.writeln("        });");
document.writeln("        function file_upload(files){");
document.writeln("            if (files.length == 0) return alert(\'请选择图片文件！\');");
document.writeln("            for(var j = 0,len = files.length; j < len; j++){");
document.writeln("                console.log(files[j]);");
document.writeln("                let imageData = new FormData();");
document.writeln("                imageData.append(\"file\", \'multipart\');");
document.writeln("                imageData.append(\"Filedata\", files[j]);");
document.writeln("                $.ajax({");
document.writeln("                    url: url,");
document.writeln("                    type: \'POST\',");
document.writeln("                    data: imageData,");
document.writeln("                    cache: false,");
document.writeln("                    contentType: false,");
document.writeln("                    processData: false,");
document.writeln("                    dataType: \'json\',");
document.writeln("                    // 图片上传成功");
document.writeln("                    success: function (result) {");
document.writeln("                        if (result.code == 1){");
document.writeln("                            $(\'.preview\').append(\'<div><img src=\"\'+result.imgurl+\'\" ><code class=\"title1\">\'+result.imgurl+\'</code></div>\');");
document.writeln("                        }else{");
document.writeln("                            layer.msg(\'第\'+j+\'个图片上传失败\');");
document.writeln("                        }");
document.writeln("                    },");
document.writeln("                    // 图片上传失败");
document.writeln("                    error: function () {");
document.writeln("                        console.log(\'图片上传失败\');");
document.writeln("                    }");
document.writeln("                });");
document.writeln("            }");
document.writeln("        }");
document.writeln("        function url_upload(){");
document.writeln("            var urls = $(\'#urls\').val();");
document.writeln("            if (urls == false) return alert(\'请输入图片链接！\');");
document.writeln("            var UrlArr = urls.split(\"\/\/n\");");
document.writeln("            $(\'#url_upload_model\').modal(\'hide\');");
document.writeln("            for(var j = 0,len = UrlArr.length; j < len; j++){");
document.writeln("                console.log(UrlArr[j]);");
document.writeln("                $.getJSON(url, {imgurl: UrlArr[j]}, function(result, textStatus) {");
document.writeln("                    if (result.code == 1){");
document.writeln("                        $(\'.preview\').append(\'<div><img src=\"\'+result.imgurl+\'\" ><code class=\"title1\">\'+result.imgurl+\'</code></div>\');");
document.writeln("                    }else{");
document.writeln("                        layer.msg(\'第\'+j+\'个图片上传失败\');");
document.writeln("                    }");
document.writeln("                    console.log(result);");
document.writeln("                });");
document.writeln("            }");
document.writeln("        }");
document.writeln("    </script>");
document.writeln("</body>");
document.writeln("</html>");