document.writeln("<!DOCTYPE html>");
document.writeln("<!-- saved from url=(0030) -->");
document.writeln("<html xmlns=\"http://www.w3.org/1999/xhtml\"><head><meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">");
document.writeln("    ");
document.writeln("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">");
document.writeln("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, user-scalable=0\">");
document.writeln("    <meta name=\"author\" content=\"latewish\">");
document.writeln("    <meta name=\"generator\" content=\"KodCloud\">");
document.writeln("    <meta name=\"renderer\" content=\"webkit\">");
document.writeln("    <meta http-equiv=\"Cache-Control\" content=\"no-siteapp\">");
document.writeln(" ");
document.writeln("    ");
document.writeln("    <title>赞助记录</title>");
document.writeln("    ");
document.writeln("    <!-- 核心样式文件 -->");
document.writeln("    <link rel=\"stylesheet\" href=\"https://js.css.qqsuu.net/donate/index.css\">");
document.writeln("    ");
document.writeln("    <script src=\"https://js.css.qqsuu.net/donate/hm.js\"></script><script src=\"https://js.css.qqsuu.net/donate/jquery.min.js\"></script>");
document.writeln("    ");
document.writeln("    <script type=\"text/javascript\">");
document.writeln("    var _hmt = _hmt || [];");
document.writeln("    (function() {");
document.writeln("    var hm = document.createElement(\"script\");");
document.writeln("    hm.src = \"你的百度统计ID\";");
document.writeln("    var s = document.getElementsByTagName(\"script\")[0]; ");
document.writeln("    s.parentNode.insertBefore(hm, s);");
document.writeln("    })();");
document.writeln("    </script>");
document.writeln("</head>");
document.writeln(" ");
document.writeln(" ");
document.writeln("<body>");
document.writeln(" ");
document.writeln("<div class=\"container\">");
document.writeln(" ");
document.writeln("<div class=\"text-center\">");
document.writeln("    <h2 class=\"web-title\"></h2>");
document.writeln("    <p>赞助记录</p>");
document.writeln("</div>");
document.writeln(" ");
document.writeln("<div class=\"donate-list\">");
document.writeln("    <dl>");
document.writeln("        <dd>时间</dd>");
document.writeln("        <dd>来源</dd>");
document.writeln("        <dd>备注</dd>");
document.writeln("        <dd>金额</dd>");
document.writeln("    </dl>");
document.writeln("    <div id=\"donate-scroll\">");
document.writeln("        <ul style=\"margin-top: -0.221291px;\">");
document.writeln("                      ");
document.writeln("                 ");
document.writeln("<!-- 开始 -->   <li>");
document.writeln("                    <span>2019/04/20  15:35</span>     <!-- 赞助时间 -->");
document.writeln("                    <span>支付宝</span>     <!-- 赞助来源 -->");
document.writeln("                    <span>用了在线音乐播放器，特此感谢 (*玉华)</span>     <!-- 赞助留言 -->");
document.writeln("                    <span>¥ 10.00</span>     <!-- 赞助金额 -->");
document.writeln("                </li>   <!-- 结束 -->");
document.writeln("                <li>");
document.writeln("                    <span>2019/04/19  15:19</span>");
document.writeln("                    <span>微信</span>");
document.writeln("                    <span>大神你好加微cr***36(*味)</span>");
document.writeln("                    <span>¥ 1.00</span>");
document.writeln("                </li> ");
document.writeln("                <li>");
document.writeln("                    <span>2019/09/10  15:35</span>");
document.writeln("                    <span>QQ</span>");
document.writeln("                    <span>谢谢大大分享 帝仙(551***46)</span>");
document.writeln("                    <span>¥ 3.00</span>");
document.writeln("                </li> ");
document.writeln("                <li>");
document.writeln("                    <span>2019/08/30  17:23</span>");
document.writeln("                    <span>微信</span>");
document.writeln("                    <span>-</span>");
document.writeln("                    <span>¥ 1.00</span>");
document.writeln("                </li> ");
document.writeln("                <li>");
document.writeln("                    <span>2019/08/26  06:14</span>");
document.writeln("                    <span>QQ</span>");
document.writeln("                    <span>最帅小“南门”！(937***156)</span>");
document.writeln("                    <span>¥ 1.00</span>");
document.writeln("                </li> ");
document.writeln("                <li>");
document.writeln("                    <span>2019/08/23  14:34</span>");
document.writeln("                    <span>微信</span>");
document.writeln("                    <span>识别出来好慢，支付宝</span>");
document.writeln("                    <span>¥ 1.00</span>");
document.writeln("                </li> ");
document.writeln("                <li>");
document.writeln("                    <span>2019/07/31  14:12</span>");
document.writeln("                    <span>微信</span>");
document.writeln("                    <span>-</span>");
document.writeln("                    <span>¥ 0.01</span>");
document.writeln("                </li> ");
document.writeln("                <li>");
document.writeln("                    <span>2019/07/07  16:59</span>");
document.writeln("                    <span>微信</span>");
document.writeln("                    <span>-</span>");
document.writeln("                    <span>¥ 1.00</span>");
document.writeln("                </li>");
document.writeln("				<li>");
document.writeln("                    <span>2019/04/23  03:58</span>");
document.writeln("                    <span>微信</span>");
document.writeln("                    <span>故*.</span>");
document.writeln("                    <span>¥ 0.81</span>");
document.writeln("                </li>                <li>");
document.writeln("                    <span>2019/07/31  14:12</span>");
document.writeln("                    <span>微信</span>");
document.writeln("                    <span>-</span>");
document.writeln("                    <span>¥ 0.01</span>");
document.writeln("                </li> ");
document.writeln("                <li>");
document.writeln("                    <span>2019/07/07  16:59</span>");
document.writeln("                    <span>微信</span>");
document.writeln("                    <span>-</span>");
document.writeln("                    <span>¥ 1.00</span>");
document.writeln("                </li>");
document.writeln("				<li>");
document.writeln("                    <span>2019/04/23  03:58</span>");
document.writeln("                    <span>微信</span>");
document.writeln("                    <span>故*.</span>");
document.writeln("                    <span>¥ 0.81</span>");
document.writeln("                </li></ul>");
document.writeln("    </div>");
document.writeln("</div>  <!-- donate-list -->");
document.writeln(" ");
document.writeln("<!--");
document.writeln("累计收到打赏 186 笔，总金额 1071.65 元。谢谢你们！");
document.writeln("-->");
document.writeln(" ");
document.writeln("<!---------------------------------------------------------------- 从这里开始修改为你自己的信息即可 ---------------------------------------------------------------->");
document.writeln(" ");
document.writeln("<div class=\"donate-note\">");
document.writeln("<p>* 打赏时请尽量留下备注，好让我知道你是谁~如果当时忘记加备注，可加 <a href=\"weixin.html\" target=\"_blank\"><font color=#000093>站主微信留言</a> 说明</p>");
document.writeln("</div>");
document.writeln(" ");
document.writeln("<div class=\"text-center\" style=\"margin-top: 15px;\">");
document.writeln("    <img src=\"../../images/zan.jpg\" title=\"支付宝、微信、手机QQ扫码打赏\"> <!-- 可替换为自己的打赏二维码 -->");
document.writeln("</div>");
document.writeln(" ");
document.writeln("<footer class=\"footer text-center\">");
document.writeln("    『感恩的心 · 感谢有你』");
document.writeln("    <p class=\"copyright\">熊猫资源 © 2019 xm08.cn</p>");
document.writeln("</footer>");
document.writeln(" ");
document.writeln(" ");
document.writeln("</div>   <!-- container -->");
document.writeln(" ");
document.writeln("<!-- 滚动代码 -->");
document.writeln("<script type=\"text/javascript\"> ");
document.writeln("function autoScroll(obj) {  ");
document.writeln("    $(obj).find(\"ul\").stop().animate({  ");
document.writeln("        marginTop: \"-39px\"  ");
document.writeln("    }, 500, function() {  ");
document.writeln("        $(this).css({marginTop : \"0px\"}).find(\"li:first\").appendTo(this);  ");
document.writeln("    });");
document.writeln("}  ");
document.writeln("$(function() {  ");
document.writeln("    setInterval(\'autoScroll(\"#donate-scroll\")\', 2000);");
document.writeln("}) ");
document.writeln("</script> ");
document.writeln(" ");
document.writeln(" ");
document.writeln(" ");
document.writeln(" ");
document.writeln("</body></html>");